name: Autograding Tests
'on':
- push
- repository_dispatch
permissions:
  checks: write
  actions: read
  contents: read
jobs:
  run-autograding-tests:
    runs-on: ubuntu-latest
    if: github.actor != 'github-classroom[bot]'
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    - name: Case 1
      id: case-1
      uses: classroom-resources/autograding-io-grader@v1
      with:
        test-name: Case 1
        setup-command: ''
        command: python main.py
        input: '10000'
        expected-output: |-
          Salary Details:
          Basic Salary:    10000.0
          DA (70%):        7000.0
          TA (30%):        3000.0
          HRA (10%):       1000.0
          Gross Salary:    21000.0
        comparison-method: contains
        timeout: 10
        max-score: 3
    - name: Case 2
      id: case-2
      uses: classroom-resources/autograding-io-grader@v1
      with:
        test-name: Case 2
        setup-command: ''
        command: python main.py
        input: '7500'
        expected-output: |-
          Salary Details:
          Basic Salary:    7500.0
          DA (70%):        5250.0
          TA (30%):        2250.0
          HRA (10%):       750.0
          Gross Salary:    15750.0
        comparison-method: contains
        timeout: 10
        max-score: 3
    - name: Case 3
      id: case-3
      uses: classroom-resources/autograding-io-grader@v1
      with:
        test-name: Case 3
        setup-command: ''
        command: python main.py
        input: '1234.5'
        expected-output: |-
          Salary Details:
          Basic Salary:    1234.5
          DA (70%):        864.15
          TA (30%):        370.35
          HRA (10%):       123.45
          Gross Salary:    2592.45
        comparison-method: contains
        timeout: 10
        max-score: 4
    - name: Autograding Reporter
      uses: classroom-resources/autograding-grading-reporter@v1
      env:
        CASE-1_RESULTS: "${{steps.case-1.outputs.result}}"
        CASE-2_RESULTS: "${{steps.case-2.outputs.result}}"
        CASE-3_RESULTS: "${{steps.case-3.outputs.result}}"
      with:
        runners: case-1,case-2,case-3
